import Head from 'next/head'
import { styled } from '../theme/stitches.config';

const Button = styled('button', {
  backgroundColor: '$green30',
  borderRadius: '20px',
  padding: '10px',
  outline: 'none',
  border: 'none',
  cursor: 'pointer',
  color: '$white',

  '&:hover': {
    backgroundColor: '$green60',
  },
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button>Button Stitches</Button>
      </main>
    </>
  )
}
